<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>

<div id="onepagecheckout_forgotbox" style="display: none;" class='popup-wrap popup-orderEnd'>
    <div class="popup-title">
        <h3><?php echo $this->__('Forgot Password?') ?></h3>
        <a class="btn-popup-close" href="javascript:close_login();"></a>
    </div>
<?php
$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
if($http_mode)
	$forgot_url	= str_replace('http:', 'https:', $forgot_url);  
?>
    <div class="popup-cont">
    <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form" autocomplete="on">
        <div class="boxcontent form_fields">
            <div style="text-align: left;"><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></div>
			<div class='full'>
				<label>
					<?php echo $this->__('Email') ?><em>*</em>
				</label>
				
				<div class="data_area">
					<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
				</div>
            </div>
        </div>
        <div class="buttons-set" style="padding-top: 10px;">
            <button style="float:right;" onclick='open_login();' type="button" class="back-link button onepagecheckout_loginlink" title="<?php echo $this->__('Login') ?>" ><span><span><?php echo $this->__('Back to Login') ?></span></span></button>
            
            
            
            <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
            <span class="please-wait" id="forgot-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
            </span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var forgotForm = new VarienForm('forgot-password-form', true);
    //]]>
    </script>
    </div>
</div>
<?php }?>